# Generated by Django 4.1.2 on 2022-10-30 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='DateOdJoining',
        ),
        migrations.AddField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='today'),
            preserve_default=False,
        ),
    ]
