# Generated by Django 4.1.2 on 2022-10-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_employees_dateodjoining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(),
        ),
    ]
