# Generated by Django 4.1.2 on 2022-10-30 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_employees_dateofjoining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeName',
            new_name='EmployeeName',
        ),
    ]
