# Generated by Django 4.1.2 on 2022-10-30 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_employename_employees_employeename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='EmployeId',
        ),
        migrations.AddField(
            model_name='employees',
            name='EmployeeId',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='Employee Id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(verbose_name='Date of joining'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='EmployeeName',
            field=models.CharField(max_length=100, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(max_length=100, verbose_name='Photo File Name'),
        ),
    ]
