# Generated by Django 4.1.2 on 2022-10-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_employees_employeid_employees_employeeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='PhotoFileName2',
            field=models.CharField(default=None, max_length=100, verbose_name='Photo File Name 2'),
        ),
    ]
