# Generated by Django 4.1.2 on 2022-10-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employees_photofilename2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='PhotoFileName',
            field=models.CharField(default=None, max_length=100, verbose_name='Photo File Name'),
        ),
    ]
