# Generated by Django 4.1.2 on 2022-10-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_employees_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='EmployeeId',
            field=models.AutoField(default=None, primary_key=True, serialize=False, verbose_name='Employee Id'),
        ),
    ]
