# Generated by Django 4.1.2 on 2022-10-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_employees_employeeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeId',
            new_name='EmployeId',
        ),
    ]
