# Generated by Django 4.1.2 on 2022-10-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_employeeid_employees_employeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeId',
            new_name='EmployeeId',
        ),
    ]
