# Generated by Django 4.1.2 on 2022-10-30 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_employeid_employees_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='PhotoFileName2',
        ),
    ]
