# Generated by Django 4.1.2 on 2022-10-30 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_employees_photofilename2'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='Image',
            field=models.ImageField(default=None, upload_to='media', verbose_name='Image Field'),
        ),
    ]
