# Generated by Django 4.1.2 on 2022-10-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_employees_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Image',
        ),
    ]
