apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: 776671337774.dkr.ecr.us-east-1.amazonaws.com/backend-api:1.1
        ports:
        - containerPort: 8081
      # - name: nginx
      #   image: nginx:1.25.1
      #   ports:
      #   - containerPort: 8080
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nginx-ingress
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#   - host: my-app.com
#     http:
#       paths:
#       - path: /api/
#         pathType: Prefix
#         backend:
#           service:
#             name: rest-api
#             port:
#               name: http
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: nginx
#             port:
#               name: http

